### ISSUE TITLE
Errors.

### ISSUE THREAD

**Issue by SummerToast** [Y-v-a-i-n/JSDefender-Deobfuscator#1]
'electron' is not recognized as an internal or external command,
operable program or batch file.

app.on("ready", createWindow), app.on("window-all-closed", (() => {
    ^

TypeError: Cannot read properties of undefined (reading 'on')
    at Object.<anonymous> (D:\bread\Downloads\JSDefender-Deobfuscator-main\index.js:26:5)

**Comment by Y-v-a-i-n** [comment]
Hello, you need to install electronJs on your machine, for this please run : 

npm install electron -g

**Comment by Y-v-a-i-n** [comment]
I will modify the batch file tonight to install it automatically, thanks for pointing it out

**Comment by Y-v-a-i-n** [comment]
and the deobfuscator works with electronJs so you don't have to run
`node .`
but
`electron .`
