### ISSUE TITLE
Failed to deobfuscate file

### ISSUE THREAD

**Issue by MDMCK10** [Y-v-a-i-n/JSDefender-Deobfuscator#2]
Hello, I have two files that are obfuscated with JSDefender and this tool succeeded on one of them, but outputs nothing on the other one.
There is no feedback or any sort of error shown, the output box is just empty.

The problematic obfuscated file can be found here: https://hastebin.com/raw/culufavicu

**Comment by Y-v-a-i-n** [comment]
Hello, sorry for the delay in answering at the moment, I have a lot of courses which means that I have very little time for myself, I'll look into it right away

**Comment by Y-v-a-i-n** [comment]
I just found out what the problem was, I had seen it not long ago but didn't think it was serious at the time, thanks for reporting it I'll fix the bugs right away and send you your code in clear

**Comment by Y-v-a-i-n** [comment]
Basically the error comes from your corrupted algorithm
```js
return��� ⵛⴸⴲ;
```
I have therefore removed `���` but I will add a function in my algorithm to signal when an error in the given program is present

A sub-obfuscation is present (obfuscator.io) but it does not interfere with the readability of the algorithm, this is a malware (password stealer)

https://pastebin.com/raw/JdZvmj38

**Comment by Y-v-a-i-n** [comment]
If you have an obfuscated code please send it to me on yvain@riseup.net, I could have fun
