### ISSUE TITLE
Issue with running on Ubuntu VM

### ISSUE THREAD

**Issue by nadrojisk** [Y-v-a-i-n/JSDefender-Deobfuscator#3]
Hello, I tried  building this on my VM today and I got some errors when running. I'm not super familiar with running electron apps so I apologize if this is an obvious mistake.

The error:
`[14123:0109/164007.288642:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.`

The app launches, but if I press the decompile button nothing occurs. 

![image](https://user-images.githubusercontent.com/37343577/211416696-ac19d15a-f233-4325-b9a7-20d12ac7144c.png)

I'm running this on remnux

**Comment by Y-v-a-i-n** [comment]
Hello, I apologize for the long response time, at the moment I'm working to pass some exams so I haven't had much time to concentrate on this, regarding your error it is not from my project. This error seems to indicate that there is a problem with the communication between the Electron application and the GPU driver of the virtual machine. There could be several reasons for this, such as a lack of resources on the virtual machine or outdated GPU drivers. Your virtual machine configuration may not be compatible with the Electron application. There may also be a conflict with other applications using GPU resources. It may be worth checking your virtual machine configuration and updating the GPU drivers if necessary. If the problem persists, you could also try disabling the graphics features of the Electron application in the startup settings. If you still haven't succeeded in unblocking this, send it to me at yvain@riseup.net, I might be able to unblock it. 

Sincerely Yvain.
